### ISSUE TITLE
Unterschied zwischen Thumbnail und Startbild auf Detailseite

### ISSUE THREAD

**Issue by emmaalouu** [kulturfinder/kulturfinder.sh-frontend#46]
Das Thumbnail in der Listenansicht unterscheidet sich von dem Startbild in der Detailansicht. Für Thumbnail und Startbild soll das gleiche Bild verwendet werden.

**Comment by tjorbo** [comment]
Aufgrund der neuen API mit fester Reihenfolge der Bilder wird dieses Ticket nicht bearbeitet
